const MOVIES_LOADED = 'MOVIES_LOADED';
const MOVIE_DETAILS_LOADED = 'MOVIE_DETAILS_LOADED';
const GENRES_LOADED = 'GENRES_LOADED';
const SORTING_METHOD_CHANGED = 'SORTING_METHOD_CHANGED';
const GENRE_ADDED = 'GENRE_ADDED';
const GENRE_REMOVED = 'GENRE_REMOVED';

export {MOVIES_LOADED, MOVIE_DETAILS_LOADED, GENRES_LOADED, SORTING_METHOD_CHANGED, GENRE_ADDED, GENRE_REMOVED};
